apiVersion: apps/v1
kind: Deployment
metadata:
name: node-app-green
namespace: app
spec:
replicas: 2
selector:
matchLabels:
app: node
color: green
template:
metadata:
labels:
app: node
color: green
spec:
containers:
- name: node
image: docker.io/pratha97/node-python-demo-node-frontend:latest
imagePullPolicy: Always
env:
- name: PYTHON_API
value: http://python-service
ports:
- containerPort: 8080
readinessProbe:
httpGet:
path: /
port: 8080
initialDelaySeconds: 5
periodSeconds: 5
livenessProbe:
httpGet:
path: /
port: 8080
initialDelaySeconds: 10
periodSeconds: 10