apiVersion: v1
kind: Service
metadata:
name: node-blue
namespace: app
spec:
selector:
app: node
color: blue
ports:
- port: 8080
targetPort: 8080
type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
name: node-green
namespace: app
spec:
selector:
app: node
color: green
ports:
- port: 8080
targetPort: 8080
type: ClusterIP