apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  namespace: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
        - name: python
          image: docker.io/pratha97/node-python-demo-python-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /api/hello
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /api/hello
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10